<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>sas</string>
	</array>
	<key>name</key>
	<string>Language of SAS</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quote</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#operator</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constant</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:((catname)\s+(\w+)))</string>
			<key>beginCaptures</key>
			<dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>CATNAME Statement</string>
			<key>end</key>
			<string>(;)</string>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:(list|clear))</string>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>keyword.operator.language_of_sas</string>
						</dict>
					</dict>
					<key>match</key>
					<string>(?i:((access)(\s*=\s*)(readonly)))</string>
					<key>name</key>
					<string>entity.name.function.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:freq))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC FREQ Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#title</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#where</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#byline</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(freq))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(compress|nlevels|noprint|page))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(data|formchar|order))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(exact))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>comment</key>
							<string>Statistic Options</string>
							<key>match</key>
							<string>(?i:(agree|barnard|binomial|bin|chisq|comor|eqor|zelen|fisher|jt|kappa|kentb|taub|lrchi|mcnem|measures|mhchi|or|oddsratio|pchi|pcorr|relrisk|riskdiff|scorr|smdcr|smdrc|stutc|tauc|trend|wtkap(pa){0,1}))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
						<dict>
							<key>comment</key>
							<string>Computation Options</string>
							<key>match</key>
							<string>\/(?i:((\s*((alpha|maxtime|n|pformat|seed)\s*=\s*)|mc|midp|point)))+</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(output))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(out))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(agree|ajchi|all|bdchi|binomial|bin|chisq|cmh|cmh1|cmh2|cmhcor|cmhga|cmhrms|cochq|contgy|cramv|eqkap|eqor|zelen|eqwkp|fisher|gamma|gs|gailsimon|jt|kappa|kentb|taub|lamcr|lamdas|lamrc|lgor|lgrrc1|lgrrc2|lrchi|mcnem|measures|mhchi|mhor|comor|mhrrc1|mhrrc2|n|nmiss|or|oddsratio|pchi|plcorr|rdif1|rdif2|relrisk|riskdiff(1|2)?|rrc(1|2)|relrisk(1|2)|rsk(1|11|12|2|21|22)|scorr|smdcr|smdrc|stutc|tauc|trend|tsymm|bowker|u|ucr|urc|wtkap(pa)?))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(tables))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>([\*\(\)]|-|--|_all_|_character_|_numeric)</string>
							<key>name</key>
							<string>keyword.operator.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\/)(?!\*)</string>
							<key>name</key>
							<string>keyword.operator.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(agree|all|binomial|bin|chisq|cl|cmh(1|2)?|fisher|gailsimon|jt|measures|missing|plcorr|relrisk|riskdiff|trend|cellchi2|cumcol|deviation|expected|missprint|peasonres|printkwts|scorout|sparse|stdres|totpct|crosslist|list|maxlevels|nocol|nocum|nofreq|nopercent|noprint|norow|nosparse|nowarn|outcum|outexpect|outpct))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(alpha|scores|contents|format|maxlevels|plots|out))(\s*=\s*)</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(test))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?i:(agree|gamma|kappa|kentb|taub|measures|pcorr|plcorr|scorr|smdcr|smdrc|stutc|tauc|wtkap(pa)?))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(weight))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(\/\s*(?i:(zeros)))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:sort))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC SORT Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#where</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#byline</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(sort))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(ascii|datecopy|force|overwrite|presorted|reverse|tagsort|nodupkey|nouniquekey|nothreads|threads|danish|ebcdic|finnish|national|norwegian|polish|swedish|equals|noequals))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(data|sortsize|dupout|out|uniqueout))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:append))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC APPEND Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#where</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(append))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(base|data|encryptkey))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(force|getsort|nowarn))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>3</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
								<key>5</key>
								<dict>
									<key>name</key>
									<string>markup.raw</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(\b(?i:((appendver)(\s*=\s*)(v6)))\b)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:contents))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC CONTENTS Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#where</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(contents))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(data|encryptkey|memtype|order|out(2)?))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(centiles|details|nodetails|directory|fmtlen|nods|noprint|short|varnum))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:compare))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC COMPARE Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#where</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#byline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#idline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#varline</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(compare))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(fuzz|maxprint|out|outstats|criterion|method|base|compare|data|comp|c))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(allobs|allstats|allvars|briefsummary|brief|nodate|noprint|nosummary|novalues|printall|stats|transpose|listall|listbase|listbaseobs|listbasevar|listcomp|listcompobs|listcompvar|listequalvar|listobs|listvar|outall|outbase|outcomp|outdif|outnoequal|outpercent|warning|error|nomissbase|nomisscomp|nomissing|note))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(with))\b</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:http))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC HTTP Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(http))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(ct|headerin|headerout|in|method|out|proxyhost|proxypassword|proxyport|proxyusername|url|webauthdomain|webpassword|webusername))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(http_tokenauth))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:soap))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC SOAP Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(soap))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(configfile|debug|envfil|enviornment|munderstand|out|proxy(domain|host|password|port|username)|soapaction|srsurl|web(authdomain|domain|password|username)|wss(authdomain|password|username)|in|service|url))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(envelope))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:printto))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC PRINTTO Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(printto))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(label|log|print|unit))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(new))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:print))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC PRINT Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#byline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#idline</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(print))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(contents|data|grandtotal_label|heading|split|sumlabel|blankline|n|obs|rows|width))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(label|sumlabel|nosumlabel|double|noobs|round|uniform))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(pageby|sumby|sum))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:standard))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC STANDARD Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#byline</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#varline</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(standard))\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(data|mean|out|std|vardef))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
						<dict>
							<key>match</key>
							<string>(?i:(exclnpwgt(s)?|replace|noprint|print|preserverawbyvalues))</string>
							<key>name</key>
							<string>entity.name.function.language_of_sas</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(freq|weight))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>entity.name.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i:(proc))\s+(?=(?i:pwencode))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>PROC PWENCODE Statement</string>
			<key>end</key>
			<string>(?i:((run|quit)\s*;))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?i:(pwencode))</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(;)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>storage.class.language_of_sas</string>
						</dict>
					</dict>
					<key>name</key>
					<string>meta.language_of_sas</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#quote</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#constant</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#blockcomment</string>
						</dict>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.function.language_of_sas</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>keyword.operator.language_of_sas</string>
								</dict>
							</dict>
							<key>match</key>
							<string>(?i:(in|out|method))(\s*=\s*)</string>
							<key>name</key>
							<string>meta.language_of_sas</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>blockcomment</key>
		<dict>
			<key>begin</key>
			<string>\/\*</string>
			<key>end</key>
			<string>\*\/</string>
			<key>name</key>
			<string>comment.block.slashstar.language_of_sas</string>
		</dict>
		<key>byline</key>
		<dict>
			<key>begin</key>
			<string>([bB][yY])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:(descending|ascending|notsorted))</string>
					<key>name</key>
					<string>entity.name.function.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;=;)[\s%]*\*</string>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>comment.line.inline.star.language_of_sas</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>^[\s%]*\*</string>
					<key>end</key>
					<string>;</string>
					<key>name</key>
					<string>comment.line.start.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<key>constant</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\b\d+)(?![&amp;a-zA-Z])</string>
					<key>name</key>
					<string>constant.numeric.language_of_sas</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\"\']\d{1,2}(?i:(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec))\d{2,4}[\"\'][dD])</string>
					<key>name</key>
					<string>constant.numeric.date.language_of_sas</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([\"\'][^\"\']*[\"\'][nN])</string>
					<key>name</key>
					<string>variable.language.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<key>fileref</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.language.language_of_sas</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.character.language_of_sas</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i:(_all_))|([_a-zA-Z][_a-zA-Z0-9]{0,7})</string>
		</dict>
		<key>idline</key>
		<dict>
			<key>begin</key>
			<string>([iI][dD])</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?i:(descending|ascending|notsorted))</string>
					<key>name</key>
					<string>entity.name.function.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<key>operator</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>([\+\-\*\^\/])</string>
					<key>name</key>
					<string>keyword.operator.arithmetic.language_of_sas</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:(eq|ne|gt|lt|ge|le|in|not|&amp;|and|or|min|max))\b</string>
					<key>name</key>
					<string>keyword.operator.comparison.language_of_sas</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([¬&lt;&gt;^~]?=(:)?|&gt;|&lt;|\||!|¦|¬|^|~|&lt;&gt;|&gt;&lt;|\|\|)</string>
					<key>name</key>
					<string>keyword.operator.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<key>quote</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\'[^\']*\'(?![ndt])</string>
					<key>name</key>
					<string>string.quoted.single.language_of_sas</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\"[^\"]*\"(?![ndt])</string>
					<key>name</key>
					<string>string.quoted.double.language_of_sas</string>
				</dict>
			</array>
		</dict>
		<key>title</key>
		<dict>
			<key>begin</key>
			<string>((?i:(title|footnote))[0-9]{0,2})</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
			</array>
		</dict>
		<key>varline</key>
		<dict>
			<key>begin</key>
			<string>(?i:(var))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
			</array>
		</dict>
		<key>where</key>
		<dict>
			<key>begin</key>
			<string>(?i:(where))</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(;)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.language_of_sas</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.language_of_sas</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#blockcomment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quote</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#operator</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constant</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.language_of_sas</string>
	<key>uuid</key>
	<string>ce8e98ae-85f0-4f55-9af8-b2a364eb9fc9</string>
</dict>
</plist>
